services:
  frontend:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "${FRONTEND_PORT}:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    deploy:
      resources:
        limits:
          memory: 2G
