#services:
#  frontend:
#    build:
#      dockerfile: ./frontend/Dockerfile
#    volumes:
#      - ./frontend:/app
#      - /app/node_modules
#    ports:
#      - "${FRONTEND_PORT}:3000"
#    environment:
#      - NODE_ENV=development