[project]
name = "crm-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django-filter>=25.2",
    "djangorestframework>=3.17.1",
    "djangorestframework-simplejwt[crypto]>=5.5.1",
    "gunicorn>=26.0.0",
    "mysqlclient>=2.2.8",
    "structlog>=25.5.0",
]
