# Generated by Django 5.2.4 on 2025-08-05 17:50

import os
import json
from django.db import migrations


def load_initial_orders_data(apps, schema_editor):
    Order = apps.get_model('crm', 'OrdersModel')
    file_path = os.path.join(
        os.path.dirname(__file__), '..', '..', '..', 'base_data_for_db', 'orders.json'
    )
    with open(file_path) as f:
        orders = json.load(f)

    for order in orders:
        Order.objects.create(
            **order
        )


def unload_initial_orders_data(apps, schema_editor):
    Order = apps.get_model('crm', 'OrdersModel')
    Order.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_orders_data, reverse_code=unload_initial_orders_data),
    ]
