# Generated by Django 5.2.4 on 2025-08-05 17:50

import os
import json
from django.db import migrations
from apps.crm.normalizers import normalize_order_choices


def load_initial_orders_data(apps, schema_editor):
    order_model = apps.get_model('crm', 'OrdersModel')
    file_path = os.path.join(
        os.path.dirname(__file__), '..', '..', '..', 'extra_data', 'base_data_for_db', 'orders.json'
    )

    if not os.path.exists(file_path):
        return

    with open(file_path, 'r', encoding='utf-8') as f:
        orders = json.load(f)

    for order in orders:
        if 'alreadyPaid' in order:
            order['already_paid'] = order.pop('alreadyPaid')

        normalized_data = normalize_order_choices(order)

        order_model.objects.create(**normalized_data)


def unload_initial_orders_data(apps, schema_editor):
    Order = apps.get_model('crm', 'OrdersModel')
    Order.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_orders_data, reverse_code=unload_initial_orders_data),
    ]
