# Generated by Django 5.2.7 on 2026-02-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20250805_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordersmodel',
            name='course',
            field=models.CharField(blank=True, choices=[('FS', 'Fullstack'), ('QAСX', 'QA Complex'), ('JCX', 'Java Complex'), ('JSCX', 'JavaScript Complex'), ('FE', 'Frontend'), ('PCX', 'Python Complex')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ordersmodel',
            name='course_type',
            field=models.CharField(blank=True, choices=[('pro', 'Pro'), ('minimal', 'Minimal'), ('premium', 'Premium'), ('incubator', 'Incubator'), ('vip', 'VIP')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordersmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordersmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('in_work', 'In Work'), ('agree', 'Agree'), ('disagree', 'Disagree'), ('dubbing', 'Dubbing')], max_length=15, null=True),
        ),
    ]
