# Generated by Django 6.0.4 on 2026-04-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_commentsmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodel',
            name='course',
            field=models.CharField(blank=True, choices=[('FS', 'Fullstack'), ('QACX', 'QA Complex'), ('JCX', 'Java Complex'), ('JSCX', 'JavaScript Complex'), ('FE', 'Frontend'), ('PCX', 'Python Complex')], max_length=10, null=True),
        ),
    ]
