# Generated by Django 5.2.15 on 2026-07-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_ordersmodel_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersmodel',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
